# Generated by Django 3.1.7 on 2021-03-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
