# Generated by Django 3.1.7 on 2021-03-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_auto_20210313_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
