# Generated by Django 3.1.6 on 2021-03-03 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_products', '0002_auto_20210303_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 3, 3, 15, 36, 5, 924212, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='add_products.clothes'),
        ),
    ]
